### ISSUE TITLE
hfl/chinese-roberta-wwm-ext-large 模型报错

### ISSUE THREAD

**Issue by XYZliang** [qukequke/bert-crf-token_classification_ner#8]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (11264x1024 and 768x6)

当
```
'roberta': (
        'transformers.BertTokenizer',
        'transformers.RobertaModel',
        'transformers.RobertaConfig',
        'hfl/chinese-roberta-wwm-ext',
    ),
MODEL = 'roberta'
```
修改为
```
'roberta': (
        'transformers.BertTokenizer',
        'transformers.RobertaModel',
        'transformers.RobertaConfig',
        'hfl/chinese-roberta-wwm-ext-large',
    ),
MODEL = 'roberta'
```
训练报错
```
Traceback (most recent call last):
  File "/data/ccks2024/ner/step_1_base_ner/plan_1_tuning_bert/model_trainer/bert-crf-token_classification_ner/train.py", line 155, in <module>
    main()
  File "/data/ccks2024/ner/step_1_base_ner/plan_1_tuning_bert/model_trainer/bert-crf-token_classification_ner/train.py", line 103, in main
    epoch_time, epoch_loss, f1_score = validate(model, dev_loader)
  File "/data/ccks2024/ner/step_1_base_ner/plan_1_tuning_bert/model_trainer/bert-crf-token_classification_ner/utils.py", line 196, in validate
    tmp_eval_loss, logits = model(**tokened_data_dict)
  File "/opt/anaconda3/envs/ccks2024szl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/ccks2024szl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/ccks2024/ner/step_1_base_ner/plan_1_tuning_bert/model_trainer/bert-crf-token_classification_ner/model.py", line 451, in forward
    logits = self.classifier(sequence_output)
  File "/opt/anaconda3/envs/ccks2024szl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/ccks2024szl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/ccks2024szl/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (11264x1024 and 768x6)
```
chinese-roberta-wwm-ext-large相关衍生模型都存在这个问题，但是chinese-roberta-wwm-ext正常

**Comment by XYZliang** [comment]
voidful/albert_chinese_xxlarge等模型也存在一样的问题
